export type FormulaItem = {
  label: string;
  tex: string;
  wide?: boolean;
};

export type FormulaCategory = {
  id: string;
  name: string;
  items: FormulaItem[];
};

const item = (label: string, tex: string, wide = false): FormulaItem =>
  wide ? { label, tex, wide } : { label, tex };

export const formulaLibrary: FormulaCategory[] = [
  {
    id: 'common',
    name: '常用',
    items: [
      item('分数', String.raw`\frac{a}{b}`),
      item('根号', String.raw`\sqrt{x}`),
      item('n 次根', String.raw`\sqrt[n]{x}`),
      item('上标', String.raw`x^{2}`),
      item('下标', String.raw`x_{i}`),
      item('上下标', String.raw`x_{i}^{n}`),
      item('圆周率', String.raw`\pi`),
      item('无穷', String.raw`\infty`),
      item('正负', String.raw`\pm`),
      item('乘号', String.raw`\times`),
      item('不等于', String.raw`\neq`),
      item('约等于', String.raw`\approx`),
      item('小于等于', String.raw`\leq`),
      item('属于', String.raw`\in`),
      item('求和', String.raw`\sum_{i=1}^{n} i`),
      item('积分', String.raw`\int_{a}^{b} f(x)\,dx`),
      item('极限', String.raw`\lim_{x \to 0} f(x)`),
      item('绝对值', String.raw`\left| x \right|`),
      item('向量', String.raw`\vec{a}`),
      item('E=mc²', String.raw`E=mc^{2}`),
    ],
  },
  {
    id: 'frac',
    name: '分数 / 根式',
    items: [
      item('分数', String.raw`\frac{a}{b}`),
      item('大分数', String.raw`\dfrac{a}{b}`),
      item('连分数', String.raw`a + \cfrac{1}{b + \cfrac{1}{c}}`, true),
      item('二项式', String.raw`\binom{n}{k}`),
      item('组合', String.raw`C_{n}^{k}`),
      item('平方根', String.raw`\sqrt{x}`),
      item('立方根', String.raw`\sqrt[3]{x}`),
      item('n 次根', String.raw`\sqrt[n]{a}`),
      item('根式分式', String.raw`\frac{\sqrt{a}}{\sqrt{b}}`),
      item('分式方程', String.raw`\frac{1}{x} + \frac{1}{y} = \frac{1}{z}`),
    ],
  },
  {
    id: 'script',
    name: '上下标',
    items: [
      item('平方', String.raw`x^{2}`),
      item('立方', String.raw`x^{3}`),
      item('幂', String.raw`a^{n}`),
      item('下标', String.raw`a_{n}`),
      item('双下标', String.raw`a_{i,j}`),
      item('上下标', String.raw`a_{i}^{j}`),
      item('前置下标', String.raw`{}_{n}P_{k}`),
      item('化学式', String.raw`H_{2}O`),
      item('同位素', String.raw`{}^{14}_{6}C`),
      item('阶乘', String.raw`n!`),
    ],
  },
  {
    id: 'calc',
    name: '微积分',
    items: [
      item('不定积分', String.raw`\int f(x)\,dx`),
      item('定积分', String.raw`\int_{a}^{b} f(x)\,dx`),
      item('二重积分', String.raw`\iint_{D} f\,dA`),
      item('三重积分', String.raw`\iiint_{V} f\,dV`),
      item('曲线积分', String.raw`\oint_{C} \vec{F}\cdot d\vec{r}`),
      item('极限', String.raw`\lim_{x \to a} f(x)`),
      item('无穷极限', String.raw`\lim_{n \to \infty} a_{n}`),
      item('导数', String.raw`f'(x)`),
      item('高阶导', String.raw`f^{(n)}(x)`),
      item('莱布尼茨', String.raw`\frac{dy}{dx}`),
      item('偏导', String.raw`\frac{\partial f}{\partial x}`),
      item('二阶偏导', String.raw`\frac{\partial^{2} f}{\partial x^{2}}`),
      item('梯度', String.raw`\nabla f`),
      item('散度', String.raw`\nabla \cdot \vec{F}`),
      item('旋度', String.raw`\nabla \times \vec{F}`),
      item('拉普拉斯', String.raw`\nabla^{2} f`),
      item('导数定义', String.raw`f'(x)=\lim_{h \to 0}\frac{f(x+h)-f(x)}{h}`, true),
      item('微积分基本定理', String.raw`\frac{d}{dx}\int_{a}^{x} f(t)\,dt = f(x)`, true),
    ],
  },
  {
    id: 'large',
    name: '大型运算',
    items: [
      item('求和', String.raw`\sum_{i=1}^{n} a_{i}`),
      item('无穷和', String.raw`\sum_{n=1}^{\infty} a_{n}`),
      item('连乘', String.raw`\prod_{i=1}^{n} a_{i}`),
      item('余积', String.raw`\coprod_{i=1}^{n} a_{i}`),
      item('并', String.raw`\bigcup_{i=1}^{n} A_{i}`),
      item('交', String.raw`\bigcap_{i=1}^{n} A_{i}`),
      item('直和', String.raw`\bigoplus_{i=1}^{n} V_{i}`),
      item('张量积', String.raw`\bigotimes_{i=1}^{n} V_{i}`),
      item('大析取', String.raw`\bigvee_{i=1}^{n} p_{i}`),
      item('大合取', String.raw`\bigwedge_{i=1}^{n} p_{i}`),
    ],
  },
  {
    id: 'greek',
    name: '希腊字母',
    items: [
      item('alpha', String.raw`\alpha`),
      item('beta', String.raw`\beta`),
      item('gamma', String.raw`\gamma`),
      item('delta', String.raw`\delta`),
      item('epsilon', String.raw`\epsilon`),
      item('varepsilon', String.raw`\varepsilon`),
      item('zeta', String.raw`\zeta`),
      item('eta', String.raw`\eta`),
      item('theta', String.raw`\theta`),
      item('vartheta', String.raw`\vartheta`),
      item('iota', String.raw`\iota`),
      item('kappa', String.raw`\kappa`),
      item('lambda', String.raw`\lambda`),
      item('mu', String.raw`\mu`),
      item('nu', String.raw`\nu`),
      item('xi', String.raw`\xi`),
      item('pi', String.raw`\pi`),
      item('varpi', String.raw`\varpi`),
      item('rho', String.raw`\rho`),
      item('varrho', String.raw`\varrho`),
      item('sigma', String.raw`\sigma`),
      item('varsigma', String.raw`\varsigma`),
      item('tau', String.raw`\tau`),
      item('upsilon', String.raw`\upsilon`),
      item('phi', String.raw`\phi`),
      item('varphi', String.raw`\varphi`),
      item('chi', String.raw`\chi`),
      item('psi', String.raw`\psi`),
      item('omega', String.raw`\omega`),
      item('Gamma', String.raw`\Gamma`),
      item('Delta', String.raw`\Delta`),
      item('Theta', String.raw`\Theta`),
      item('Lambda', String.raw`\Lambda`),
      item('Xi', String.raw`\Xi`),
      item('Pi', String.raw`\Pi`),
      item('Sigma', String.raw`\Sigma`),
      item('Upsilon', String.raw`\Upsilon`),
      item('Phi', String.raw`\Phi`),
      item('Psi', String.raw`\Psi`),
      item('Omega', String.raw`\Omega`),
      item('aleph', String.raw`\aleph`),
      item('hbar', String.raw`\hbar`),
      item('ell', String.raw`\ell`),
      item('wp', String.raw`\wp`),
      item('Re', String.raw`\Re`),
      item('Im', String.raw`\Im`),
    ],
  },
  {
    id: 'binary',
    name: '运算符号',
    items: [
      item('加', String.raw`+`),
      item('减', String.raw`-`),
      item('正负', String.raw`\pm`),
      item('负正', String.raw`\mp`),
      item('乘', String.raw`\times`),
      item('除', String.raw`\div`),
      item('点乘', String.raw`\cdot`),
      item('星', String.raw`\ast`),
      item('星号', String.raw`\star`),
      item('圆圈', String.raw`\circ`),
      item('实心圆', String.raw`\bullet`),
      item('直和', String.raw`\oplus`),
      item('直减', String.raw`\ominus`),
      item('张量', String.raw`\otimes`),
      item('圆除', String.raw`\oslash`),
      item('圆点', String.raw`\odot`),
      item('交', String.raw`\cap`),
      item('并', String.raw`\cup`),
      item('析取', String.raw`\vee`),
      item('合取', String.raw`\wedge`),
      item('集合减', String.raw`\setminus`),
      item('wr', String.raw`\wr`),
      item('amalg', String.raw`\amalg`),
      item('uplus', String.raw`\uplus`),
    ],
  },
  {
    id: 'rel',
    name: '关系符号',
    items: [
      item('等于', String.raw`=`),
      item('不等于', String.raw`\neq`),
      item('恒等', String.raw`\equiv`),
      item('约等于', String.raw`\approx`),
      item('相似', String.raw`\sim`),
      item('同构', String.raw`\simeq`),
      item('合同', String.raw`\cong`),
      item('正比', String.raw`\propto`),
      item('小于', String.raw`<`),
      item('大于', String.raw`>`),
      item('小于等于', String.raw`\leq`),
      item('大于等于', String.raw`\geq`),
      item('远小于', String.raw`\ll`),
      item('远大于', String.raw`\gg`),
      item('先于', String.raw`\prec`),
      item('后于', String.raw`\succ`),
      item('属于', String.raw`\in`),
      item('不属于', String.raw`\notin`),
      item('包含于', String.raw`\subset`),
      item('包含', String.raw`\supset`),
      item('子集', String.raw`\subseteq`),
      item('超集', String.raw`\supseteq`),
      item('整除', String.raw`\mid`),
      item('平行', String.raw`\parallel`),
      item('垂直', String.raw`\perp`),
      item('模型', String.raw`\models`),
      item('推出', String.raw`\vdash`),
      item('约等于+', String.raw`\asymp`),
      item('近似', String.raw`\approxeq`),
      item('三角形', String.raw`\triangleq`),
    ],
  },
  {
    id: 'arrow',
    name: '箭头',
    items: [
      item('右箭头', String.raw`\rightarrow`),
      item('左箭头', String.raw`\leftarrow`),
      item('双向', String.raw`\leftrightarrow`),
      item('推出', String.raw`\Rightarrow`),
      item('逆推', String.raw`\Leftarrow`),
      item('等价', String.raw`\Leftrightarrow`),
      item('映射', String.raw`\mapsto`),
      item('嵌入', String.raw`\hookrightarrow`),
      item('上箭头', String.raw`\uparrow`),
      item('下箭头', String.raw`\downarrow`),
      item('长右', String.raw`\longrightarrow`),
      item('长左', String.raw`\longleftarrow`),
      item('长双向', String.raw`\longleftrightarrow`),
      item('东北', String.raw`\nearrow`),
      item('东南', String.raw`\searrow`),
      item('钩右', String.raw`\rightharpoonup`),
      item('钩左', String.raw`\leftharpoonup`),
      item('向量箭头', String.raw`\overrightarrow{AB}`),
    ],
  },
  {
    id: 'delim',
    name: '括号',
    items: [
      item('圆括号', String.raw`\left( a \right)`),
      item('方括号', String.raw`\left[ a \right]`),
      item('花括号', String.raw`\left\{ a \right\}`),
      item('尖括号', String.raw`\left\langle a \right\rangle`),
      item('绝对值', String.raw`\left| a \right|`),
      item('范数', String.raw`\left\| a \right\|`),
      item('下取整', String.raw`\lfloor x \rfloor`),
      item('上取整', String.raw`\lceil x \rceil`),
      item('二项式括号', String.raw`\left( \frac{a}{b} \right)`),
      item('分段', String.raw`\begin{cases} a & x>0 \\ b & x\le 0 \end{cases}`, true),
    ],
  },
  {
    id: 'matrix',
    name: '矩阵',
    items: [
      item('2×2', String.raw`\begin{pmatrix} a & b \\ c & d \end{pmatrix}`),
      item('3×3', String.raw`\begin{pmatrix} a & b & c \\ d & e & f \\ g & h & i \end{pmatrix}`, true),
      item('方括号阵', String.raw`\begin{bmatrix} a & b \\ c & d \end{bmatrix}`),
      item('行列式', String.raw`\begin{vmatrix} a & b \\ c & d \end{vmatrix}`),
      item('双竖线阵', String.raw`\begin{Vmatrix} a & b \\ c & d \end{Vmatrix}`),
      item('无括号阵', String.raw`\begin{matrix} a & b \\ c & d \end{matrix}`),
      item('单位阵', String.raw`I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}`),
      item('转置', String.raw`A^{\mathrm{T}}`),
      item('逆矩阵', String.raw`A^{-1}`),
      item('行列式符号', String.raw`\det(A)`),
    ],
  },
  {
    id: 'func',
    name: '函数',
    items: [
      item('sin', String.raw`\sin x`),
      item('cos', String.raw`\cos x`),
      item('tan', String.raw`\tan x`),
      item('cot', String.raw`\cot x`),
      item('sec', String.raw`\sec x`),
      item('csc', String.raw`\csc x`),
      item('arcsin', String.raw`\arcsin x`),
      item('arccos', String.raw`\arccos x`),
      item('arctan', String.raw`\arctan x`),
      item('sinh', String.raw`\sinh x`),
      item('cosh', String.raw`\cosh x`),
      item('tanh', String.raw`\tanh x`),
      item('log', String.raw`\log x`),
      item('ln', String.raw`\ln x`),
      item('lg', String.raw`\lg x`),
      item('exp', String.raw`\exp x`),
      item('max', String.raw`\max`),
      item('min', String.raw`\min`),
      item('sup', String.raw`\sup`),
      item('inf', String.raw`\inf`),
      item('lim', String.raw`\lim`),
      item('det', String.raw`\det`),
      item('deg', String.raw`\deg`),
      item('gcd', String.raw`\gcd`),
      item('mod', String.raw`a \bmod n`),
      item('三角函数恒等', String.raw`\sin^{2}x + \cos^{2}x = 1`, true),
    ],
  },
  {
    id: 'accent',
    name: '重音 / 装饰',
    items: [
      item('帽', String.raw`\hat{a}`),
      item('宽帽', String.raw`\widehat{AB}`),
      item('波浪', String.raw`\tilde{a}`),
      item('宽波浪', String.raw`\widetilde{AB}`),
      item('横杠', String.raw`\bar{a}`),
      item('上划线', String.raw`\overline{AB}`),
      item('下划线', String.raw`\underline{AB}`),
      item('向量', String.raw`\vec{a}`),
      item('点', String.raw`\dot{a}`),
      item('双点', String.raw`\ddot{a}`),
      item('锐音', String.raw`\acute{a}`),
      item('抑音', String.raw`\grave{a}`),
      item('短音', String.raw`\breve{a}`),
      item('对号', String.raw`\check{a}`),
      item('上括号', String.raw`\overbrace{a+b+c}`),
      item('下括号', String.raw`\underbrace{a+b+c}`),
    ],
  },
  {
    id: 'set',
    name: '集合 / 逻辑',
    items: [
      item('空集', String.raw`\emptyset`),
      item('自然数', String.raw`\mathbb{N}`),
      item('整数', String.raw`\mathbb{Z}`),
      item('有理数', String.raw`\mathbb{Q}`),
      item('实数', String.raw`\mathbb{R}`),
      item('复数', String.raw`\mathbb{C}`),
      item('属于', String.raw`x \in A`),
      item('不属于', String.raw`x \notin A`),
      item('子集', String.raw`A \subseteq B`),
      item('并集', String.raw`A \cup B`),
      item('交集', String.raw`A \cap B`),
      item('差集', String.raw`A \setminus B`),
      item('全集', String.raw`U`),
      item('补集', String.raw`A^{c}`),
      item('任意', String.raw`\forall`),
      item('存在', String.raw`\exists`),
      item('不存在', String.raw`\nexists`),
      item('否定', String.raw`\neg p`),
      item('且', String.raw`p \land q`),
      item('或', String.raw`p \lor q`),
      item('蕴含', String.raw`p \Rightarrow q`),
      item('等价', String.raw`p \Leftrightarrow q`),
      item('因此', String.raw`\therefore`),
      item('因为', String.raw`\because`),
    ],
  },
  {
    id: 'classic',
    name: '经典公式',
    items: [
      item('质能方程', String.raw`E=mc^{2}`),
      item('二次求根', String.raw`x = \frac{-b \pm \sqrt{b^{2}-4ac}}{2a}`, true),
      item('勾股定理', String.raw`a^{2} + b^{2} = c^{2}`),
      item('欧拉恒等式', String.raw`e^{i\pi} + 1 = 0`),
      item('欧拉公式', String.raw`e^{ix} = \cos x + i\sin x`, true),
      item('牛顿第二定律', String.raw`F = ma`),
      item('万有引力', String.raw`F = G\frac{m_{1}m_{2}}{r^{2}}`),
      item('库仑定律', String.raw`F = k\frac{q_{1}q_{2}}{r^{2}}`),
      item('动能', String.raw`E_{k} = \frac{1}{2}mv^{2}`),
      item('理想气体', String.raw`PV = nRT`),
      item('泰勒展开', String.raw`f(x) = \sum_{n=0}^{\infty}\frac{f^{(n)}(a)}{n!}(x-a)^{n}`, true),
      item('二项式定理', String.raw`(a+b)^{n} = \sum_{k=0}^{n}\binom{n}{k}a^{n-k}b^{k}`, true),
      item('高斯积分', String.raw`\int_{-\infty}^{\infty} e^{-x^{2}}\,dx = \sqrt{\pi}`, true),
      item('正态分布', String.raw`f(x) = \frac{1}{\sqrt{2\pi}\sigma}e^{-\frac{(x-\mu)^{2}}{2\sigma^{2}}}`, true),
      item('贝叶斯', String.raw`P(A|B) = \frac{P(B|A)P(A)}{P(B)}`),
      item('傅里叶级数', String.raw`f(x) = \frac{a_{0}}{2} + \sum_{n=1}^{\infty}(a_{n}\cos nx + b_{n}\sin nx)`, true),
      item('柯西-施瓦茨', String.raw`|\langle u,v\rangle|^{2} \leq \|u\|^{2}\|v\|^{2}`, true),
      item('正弦定理', String.raw`\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}`, true),
      item('余弦定理', String.raw`c^{2} = a^{2} + b^{2} - 2ab\cos C`, true),
      item('圆面积', String.raw`S = \pi r^{2}`),
      item('球体积', String.raw`V = \frac{4}{3}\pi r^{3}`),
      item('对数换底', String.raw`\log_{b}a = \frac{\log_{c}a}{\log_{c}b}`),
      item('链式法则', String.raw`(f\circ g)' = (f'\circ g)\,g'`),
      item('洛必达', String.raw`\lim_{x\to a}\frac{f(x)}{g(x)} = \lim_{x\to a}\frac{f'(x)}{g'(x)}`, true),
      item('格林公式', String.raw`\oint_{C}P\,dx + Q\,dy = \iint_{D}\left(\frac{\partial Q}{\partial x}-\frac{\partial P}{\partial y}\right)dA`, true),
      item('薛定谔方程', String.raw`i\hbar\frac{\partial}{\partial t}\Psi = \hat{H}\Psi`, true),
      item('麦克斯韦散度', String.raw`\nabla \cdot \vec{E} = \frac{\rho}{\varepsilon_{0}}`),
      item('波动方程', String.raw`\frac{\partial^{2}u}{\partial t^{2}} = c^{2}\nabla^{2}u`),
      item('热传导', String.raw`\frac{\partial u}{\partial t} = k\nabla^{2}u`),
      item('拉普拉斯方程', String.raw`\nabla^{2}u = 0`),
    ],
  },
];
